In [1]:
import numpy as np
import tensorflow as tf
import time
import sys
from utils import Logger, pcm2gm
from bp_7 import BP_Decoder, E2EModel, test_model_bp

In [2]:
# time_now = time.strftime('%m%d%H%M%S', time.localtime(time.time()))
# os.makedirs('./Logs/' + time_now)


# # log
# logfile = open('./bp_dec_result/'+time_now+'.txt', 'a')
# sys.stdout = Logger('./bp_dec_result/'+time_now+'.txt', sys.stdout)

## 96LDPC

In [4]:
n = 96
k = 48

file_h = './Logs/1129044603/mat/episode_297step_1reward_8.208328731330102.txt'
pcm = np.loadtxt(file_h, dtype=np.int32)
gnm = pcm2gm(pcm, verify_results=True)

num_iter = 8
tf.random.set_seed(2)
bp_decoder = BP_Decoder(pcm = pcm,
                         num_iter = num_iter)
e2e_model = E2EModel(gnm, bp_decoder)
print('Code: ', n, ',', k, 'from', file_h)
print('Iteration: ', num_iter)

# test_params = [snr_low, snr_high, max_batch, block_per_batch, num_target_block_errors]
test_model_bp(e2e_model, [1.0, 6.0, 10000, 10000, 500])

Code:  96 , 48 from ./Logs/1129044603/mat/episode_297step_1reward_8.208328731330102.txt
Iteration:  8
SNR [1.], ber = 7.32938e-02, bler = 6.67000e-01, block_num = 10000, run_time = 1.70s
SNR [2.], ber = 2.93260e-02, bler = 3.18300e-01, block_num = 10000, run_time = 0.28s
SNR [3.], ber = 6.66667e-03, bler = 8.31000e-02, block_num = 10000, run_time = 0.26s
SNR [4.], ber = 8.51667e-04, bler = 1.21400e-02, block_num = 50000, run_time = 2.21s
SNR [5.], ber = 4.55019e-05, bler = 7.60606e-04, block_num = 660000, run_time = 28.51s
SNR [6.], ber = 1.71223e-06, bler = 2.80201e-05, block_num = 17880000, run_time = 640.89s


(array([7.32937500e-02, 2.93260417e-02, 6.66666667e-03, 8.51666667e-04,
        4.55018939e-05, 1.71222502e-06]),
 array([6.67000000e-01, 3.18300000e-01, 8.31000000e-02, 1.21400000e-02,
        7.60606061e-04, 2.80201342e-05]))

In [2]:
n = 96
k = 48

file_h = './Logs/1129044603/mat/episode_10step_1reward_8.287184590953462.txt'
pcm = np.loadtxt(file_h, dtype=np.int32)
gnm = pcm2gm(pcm, verify_results=True)

num_iter = 8
tf.random.set_seed(2)
bp_decoder = BP_Decoder(pcm = pcm,
                         num_iter = num_iter)
e2e_model = E2EModel(gnm, bp_decoder)
print('Code: ', n, ',', k, 'from', file_h)
print('Iteration: ', num_iter)

# test_params = [snr_low, snr_high, max_batch, block_per_batch, num_target_block_errors]
test_model_bp(e2e_model, [1.0, 6.0, 10000, 10000, 500])

Code:  96 , 48 from ./Logs/1129044603/mat/episode_10step_1reward_8.287184590953462.txt
Iteration:  8
SNR [1.], ber = 6.97750e-02, bler = 6.53500e-01, block_num = 10000, run_time = 2.35s
SNR [2.], ber = 2.68250e-02, bler = 3.00400e-01, block_num = 10000, run_time = 0.25s
SNR [3.], ber = 6.22500e-03, bler = 8.17000e-02, block_num = 10000, run_time = 0.24s
SNR [4.], ber = 7.04583e-04, bler = 1.10600e-02, block_num = 50000, run_time = 1.20s
SNR [5.], ber = 4.12224e-05, bler = 7.41176e-04, block_num = 680000, run_time = 26.79s
SNR [6.], ber = 1.26788e-06, bler = 2.59049e-05, block_num = 19340000, run_time = 607.21s


(array([6.97750000e-02, 2.68250000e-02, 6.22500000e-03, 7.04583333e-04,
        4.12224265e-05, 1.26788176e-06]),
 array([6.53500000e-01, 3.00400000e-01, 8.17000000e-02, 1.10600000e-02,
        7.41176471e-04, 2.59048604e-05]))

In [2]:
n = 96
k = 48

file_h = './Matrix/LDPC_96_48_chk.txt'
pcm = np.loadtxt(file_h, dtype=np.int32)
gnm = pcm2gm(pcm, verify_results=True)

num_iter = 8
tf.random.set_seed(2)
bp_decoder = BP_Decoder(pcm = pcm,
                         num_iter = num_iter)
e2e_model = E2EModel(gnm, bp_decoder)
print('Code: ', n, ',', k, 'from', file_h)
print('Iteration: ', num_iter)

# test_params = [snr_low, snr_high, max_batch, block_per_batch, num_target_block_errors]
test_model_bp(e2e_model, [1.0, 6.0, 10000, 10000, 500])

Code:  96 , 48 from ./Matrix/LDPC_96_48_chk.txt
Iteration:  8
SNR [1.], ber = 7.65646e-02, bler = 6.86500e-01, block_num = 10000, run_time = 1.96s
SNR [2.], ber = 3.12771e-02, bler = 3.31000e-01, block_num = 10000, run_time = 0.22s
SNR [3.], ber = 6.84792e-03, bler = 8.34000e-02, block_num = 10000, run_time = 0.22s
SNR [4.], ber = 9.19010e-04, bler = 1.31500e-02, block_num = 40000, run_time = 0.86s
SNR [5.], ber = 5.60185e-05, bler = 9.27778e-04, block_num = 540000, run_time = 11.77s
SNR [6.], ber = 1.82400e-06, bler = 2.99104e-05, block_num = 16750000, run_time = 364.32s


KeyboardInterrupt: 

## DRL Code - BCH Iter 2

In [4]:
n = 63
k = 45

file_h = './Logs/1109051227/mat/episode_453step_1reward_11.324031767471412.txt'
pcm = np.loadtxt(file_h, dtype=np.int32)
gnm = pcm2gm(pcm, verify_results=True)

num_iter = 8
tf.random.set_seed(2)
bp_decoder = BP_Decoder(pcm = pcm,
                         num_iter = num_iter)
e2e_model = E2EModel(gnm, bp_decoder)
print('Code: ', n, ',', k, 'from', file_h)
print('Iteration: ', num_iter)

# test_params = [snr_low, snr_high, max_batch, block_per_batch, num_target_block_errors]
test_model_bp(e2e_model, [1.0, 8.0, 10000, 10000, 500])

Code:  63 , 45 from ./Logs/1109051227/mat/episode_453step_1reward_11.324031767471412.txt
Iteration:  8
SNR [1.], ber = 7.95683e-02, bler = 8.67400e-01, block_num = 10000, run_time = 1.44s
SNR [2.], ber = 4.46651e-02, bler = 5.82100e-01, block_num = 10000, run_time = 0.06s
SNR [3.], ber = 1.82349e-02, bler = 2.64000e-01, block_num = 10000, run_time = 0.06s
SNR [4.], ber = 4.86508e-03, bler = 7.74000e-02, block_num = 10000, run_time = 0.06s
SNR [5.], ber = 9.09524e-04, bler = 1.56750e-02, block_num = 40000, run_time = 0.22s
SNR [6.], ber = 1.00454e-04, bler = 1.82857e-03, block_num = 280000, run_time = 1.54s
SNR [7.], ber = 6.63984e-06, bler = 1.41127e-04, block_num = 3550000, run_time = 19.36s
SNR [8.], ber = 3.97385e-07, bler = 8.83286e-06, block_num = 56720000, run_time = 308.41s


(array([7.95682540e-02, 4.46650794e-02, 1.82349206e-02, 4.86507937e-03,
        9.09523810e-04, 1.00453515e-04, 6.63983903e-06, 3.97385094e-07]),
 array([8.67400000e-01, 5.82100000e-01, 2.64000000e-01, 7.74000000e-02,
        1.56750000e-02, 1.82857143e-03, 1.41126761e-04, 8.83286319e-06]))

## DRL Code - BCH Iter 1

In [8]:
n = 63
k = 45

file_h = './Logs/1107234737/mat/episode_263step_1reward_10.27523168902498.txt'
pcm = np.loadtxt(file_h, dtype=np.int32)
gnm = pcm2gm(pcm, verify_results=True)

num_iter = 8
tf.random.set_seed(2)
bp_decoder = BP_Decoder(pcm = pcm,
                         num_iter = num_iter)
e2e_model = E2EModel(gnm, bp_decoder)
print('Code: ', n, ',', k, 'from', file_h)
print('Iteration: ', num_iter)

# test_params = [snr_low, snr_high, max_batch, block_per_batch, num_target_block_errors]
test_model_bp(e2e_model, [1.0, 8.0, 10000, 10000, 500])

Code:  63 , 45 from ./Logs/1107234737/mat/episode_263step_1reward_10.27523168902498.txt
Iteration:  8
SNR [1.], ber = 7.74587e-02, bler = 8.55200e-01, block_num = 10000, run_time = 1.43s
SNR [2.], ber = 4.24857e-02, bler = 5.56800e-01, block_num = 10000, run_time = 0.07s
SNR [3.], ber = 1.68524e-02, bler = 2.49000e-01, block_num = 10000, run_time = 0.06s
SNR [4.], ber = 4.52698e-03, bler = 7.31000e-02, block_num = 10000, run_time = 0.06s
SNR [5.], ber = 7.63095e-04, bler = 1.43500e-02, block_num = 40000, run_time = 0.21s
SNR [6.], ber = 9.81481e-05, bler = 2.11667e-03, block_num = 240000, run_time = 1.16s
SNR [7.], ber = 9.49328e-06, bler = 2.40865e-04, block_num = 2080000, run_time = 9.96s
SNR [8.], ber = 9.30753e-07, bler = 2.44282e-05, block_num = 20550000, run_time = 98.26s


(array([7.74587302e-02, 4.24857143e-02, 1.68523810e-02, 4.52698413e-03,
        7.63095238e-04, 9.81481481e-05, 9.49328449e-06, 9.30753485e-07]),
 array([8.55200000e-01, 5.56800000e-01, 2.49000000e-01, 7.31000000e-02,
        1.43500000e-02, 2.11666667e-03, 2.40865385e-04, 2.44282238e-05]))

In [3]:
n = 63
k = 45

file_h = './Matrix/BCH_63_45_chk.txt'
pcm = np.loadtxt(file_h, dtype=np.int32)
gnm = pcm2gm(pcm, verify_results=True)

num_iter = 8
tf.random.set_seed(2)
bp_decoder = BP_Decoder(pcm = pcm,
                         num_iter = num_iter)
e2e_model = E2EModel(gnm, bp_decoder)
print('Code: ', n, ',', k, 'from', file_h)
print('Iteration: ', num_iter)

# test_params = [snr_low, snr_high, max_batch, block_per_batch, num_target_block_errors]
test_model_bp(e2e_model, [1.0, 8.0, 10000, 10000, 500])

Code:  63 , 45 from ./Matrix/BCH_63_45_chk.txt
Iteration:  8
SNR [1.], ber = 8.90841e-02, bler = 9.69900e-01, block_num = 10000, run_time = 2.74s
SNR [2.], ber = 6.03143e-02, bler = 8.16800e-01, block_num = 10000, run_time = 0.19s
SNR [3.], ber = 3.36365e-02, bler = 5.20100e-01, block_num = 10000, run_time = 0.22s
SNR [4.], ber = 1.47968e-02, bler = 2.36800e-01, block_num = 10000, run_time = 0.21s
SNR [5.], ber = 5.55238e-03, bler = 8.32000e-02, block_num = 10000, run_time = 0.18s
SNR [6.], ber = 1.52063e-03, bler = 2.23333e-02, block_num = 30000, run_time = 0.49s
SNR [7.], ber = 2.77778e-04, bler = 4.28333e-03, block_num = 120000, run_time = 1.87s
SNR [8.], ber = 4.44841e-05, bler = 6.38750e-04, block_num = 800000, run_time = 11.97s


(array([8.90841270e-02, 6.03142857e-02, 3.36365079e-02, 1.47968254e-02,
        5.55238095e-03, 1.52063492e-03, 2.77777778e-04, 4.44841270e-05]),
 array([9.69900000e-01, 8.16800000e-01, 5.20100000e-01, 2.36800000e-01,
        8.32000000e-02, 2.23333333e-02, 4.28333333e-03, 6.38750000e-04]))

## DRL Code - Iter 3

In [ ]:
n = 32
k = 16

file_h = './Logs/1106074917/mat/episode_178step_1reward_10.555698805138144.txt'
pcm = np.loadtxt(file_h, dtype=np.int32)
gnm = pcm2gm(pcm, verify_results=True)

num_iter = 8
tf.random.set_seed(2)
bp_decoder = BP_Decoder(pcm = pcm,
                         num_iter = num_iter)
e2e_model = E2EModel(gnm, bp_decoder)
print('Code: ', n, ',', k, 'from', file_h)
print('Iteration: ', num_iter)

# test_params = [snr_low, snr_high, max_batch, block_per_batch, num_target_block_errors]
test_model_bp(e2e_model, [1.0, 8.0, 10000, 10000, 500])

In [ ]:
n = 32
k = 16

file_h = './Logs/1106074917/mat/episode_178step_1reward_10.555698805138144.txt'
pcm = np.loadtxt(file_h, dtype=np.int32)
gnm = pcm2gm(pcm, verify_results=True)

num_iter = 30
tf.random.set_seed(2)
bp_decoder = BP_Decoder(pcm = pcm,
                         num_iter = num_iter)
e2e_model = E2EModel(gnm, bp_decoder)
print('Code: ', n, ',', k, 'from', file_h)
print('Iteration: ', num_iter)

# test_params = [snr_low, snr_high, max_batch, block_per_batch, num_target_block_errors]
test_model_bp(e2e_model, [1.0, 8.0, 10000, 10000, 500])

In [ ]:
n = 32
k = 16

file_h = './Logs/1106074917/mat/episode_178step_1reward_10.555698805138144.txt'
pcm = np.loadtxt(file_h, dtype=np.int32)
gnm = pcm2gm(pcm, verify_results=True)

num_iter = 50
tf.random.set_seed(2)
bp_decoder = BP_Decoder(pcm = pcm,
                         num_iter = num_iter)
e2e_model = E2EModel(gnm, bp_decoder)
print('Code: ', n, ',', k, 'from', file_h)
print('Iteration: ', num_iter)

# test_params = [snr_low, snr_high, max_batch, block_per_batch, num_target_block_errors]
test_model_bp(e2e_model, [1.0, 8.0, 10000, 10000, 500])

## DRL Codes - Iter 1

In [ ]:
n = 32
k = 16

file_h = './Logs/1027041248/mat/episode_93step_0reward_9.493517355730951.txt'
pcm = np.loadtxt(file_h, dtype=np.int32)
gnm = pcm2gm(pcm, verify_results=True)

num_iter = 8
tf.random.set_seed(2)
bp_decoder = BP_Decoder(pcm = pcm,
                         num_iter = num_iter)
e2e_model = E2EModel(gnm, bp_decoder)
print('Code: ', n, ',', k, 'from', file_h)
print('Iteration: ', num_iter)

# test_params = [snr_low, snr_high, max_batch, block_per_batch, num_target_block_errors]
test_model_bp(e2e_model, [1.0, 8.0, 10000, 10000, 500])

In [ ]:
n = 32
k = 16

file_h = './Logs/1027041248/mat/episode_93step_0reward_9.493517355730951.txt'
pcm = np.loadtxt(file_h, dtype=np.int32)
gnm = pcm2gm(pcm, verify_results=True)

num_iter = 30
tf.random.set_seed(2)
bp_decoder = BP_Decoder(pcm = pcm,
                         num_iter = num_iter)
e2e_model = E2EModel(gnm, bp_decoder)
print('Code: ', n, ',', k, 'from', file_h)
print('Iteration: ', num_iter)

# test_params = [snr_low, snr_high, max_batch, block_per_batch, num_target_block_errors]
test_model_bp(e2e_model, [1.0, 8.0, 10000, 10000, 500])

In [ ]:
n = 32
k = 16

file_h = './Logs/1027041248/mat/episode_88step_0reward_9.604011982945474.txt'
pcm = np.loadtxt(file_h, dtype=np.int32)
gnm = pcm2gm(pcm, verify_results=True)

num_iter = 8
tf.random.set_seed(2)
bp_decoder = BP_Decoder(pcm = pcm,
                         num_iter = num_iter)
e2e_model = E2EModel(gnm, bp_decoder)
print('Code: ', n, ',', k, 'from', file_h)
print('Iteration: ', num_iter)

# test_params = [snr_low, snr_high, max_batch, block_per_batch, num_target_block_errors]
test_model_bp(e2e_model, [1.0, 8.0, 10000, 10000, 500])

In [ ]:
n = 32
k = 16

file_h = './Logs/1027041248/mat/episode_88step_0reward_9.604011982945474.txt'
pcm = np.loadtxt(file_h, dtype=np.int32)
gnm = pcm2gm(pcm, verify_results=True)

num_iter = 30
tf.random.set_seed(2)
bp_decoder = BP_Decoder(pcm = pcm,
                         num_iter = num_iter)
e2e_model = E2EModel(gnm, bp_decoder)
print('Code: ', n, ',', k, 'from', file_h)
print('Iteration: ', num_iter)

# test_params = [snr_low, snr_high, max_batch, block_per_batch, num_target_block_errors]
test_model_bp(e2e_model, [1.0, 8.0, 10000, 10000, 500])

In [ ]:
n = 32
k = 16

file_h = './Logs/1027041248/mat/episode_50step_1reward_9.4140517057528.txt'
pcm = np.loadtxt(file_h, dtype=np.int32)
gnm = pcm2gm(pcm, verify_results=True)

num_iter = 8
tf.random.set_seed(2)
bp_decoder = BP_Decoder(pcm = pcm,
                         num_iter = num_iter)
e2e_model = E2EModel(gnm, bp_decoder)
print('Code: ', n, ',', k, 'from', file_h)
print('Iteration: ', num_iter)

# test_params = [snr_low, snr_high, max_batch, block_per_batch, num_target_block_errors]
test_model_bp(e2e_model, [1.0, 8.0, 10000, 10000, 500])

In [ ]:
n = 32
k = 16

file_h = './Logs/1027041248/mat/episode_50step_1reward_9.4140517057528.txt'
pcm = np.loadtxt(file_h, dtype=np.int32)
gnm = pcm2gm(pcm, verify_results=True)

num_iter = 30
tf.random.set_seed(2)
bp_decoder = BP_Decoder(pcm = pcm,
                         num_iter = num_iter)
e2e_model = E2EModel(gnm, bp_decoder)
print('Code: ', n, ',', k, 'from', file_h)
print('Iteration: ', num_iter)

# test_params = [snr_low, snr_high, max_batch, block_per_batch, num_target_block_errors]
test_model_bp(e2e_model, [1.0, 8.0, 10000, 10000, 500])

In [ ]:
n = 32
k = 16

file_h = './Logs/1027041248/mat/episode_51step_0reward_9.516821236790413.txt'
pcm = np.loadtxt(file_h, dtype=np.int32)
gnm = pcm2gm(pcm, verify_results=True)

num_iter = 8
tf.random.set_seed(2)
bp_decoder = BP_Decoder(pcm = pcm,
                         num_iter = num_iter)
e2e_model = E2EModel(gnm, bp_decoder)
print('Code: ', n, ',', k, 'from', file_h)
print('Iteration: ', num_iter)

# test_params = [snr_low, snr_high, max_batch, block_per_batch, num_target_block_errors]
test_model_bp(e2e_model, [1.0, 8.0, 10000, 10000, 500])

In [ ]:
n = 32
k = 16

file_h = './Logs/1027041248/mat/episode_51step_0reward_9.516821236790413.txt'
pcm = np.loadtxt(file_h, dtype=np.int32)
gnm = pcm2gm(pcm, verify_results=True)

num_iter = 30
tf.random.set_seed(2)
bp_decoder = BP_Decoder(pcm = pcm,
                         num_iter = num_iter)
e2e_model = E2EModel(gnm, bp_decoder)
print('Code: ', n, ',', k, 'from', file_h)
print('Iteration: ', num_iter)

# test_params = [snr_low, snr_high, max_batch, block_per_batch, num_target_block_errors]
test_model_bp(e2e_model, [1.0, 8.0, 10000, 10000, 500])