In [1]:
import numpy as np
import tensorflow as tf
import time
import os
import sys
from utils import Logger, pcm2gm
from ewgnn_7 import GNN_Decoder, train_model_gnn, test_model_gnn
from bp_7 import E2EModel

In [2]:
time_now = time.strftime('%m%d%H%M%S', time.localtime(time.time()))
os.makedirs('./gnn_dec_result/'+time_now)

# log
logfile = open('./gnn_dec_result/'+time_now+'/log.txt', 'a')
sys.stdout = Logger('./gnn_dec_result/'+time_now+'/log.txt', sys.stdout)

Code:  32 , 16 drl from ./Logs/1106074917/mat/episode_178step_1reward_10.555698805138144.txt
Iteration:  8
Multi-loss:  True
Model: "e2e_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 gnn__decoder (GNN_Decoder)  multiple                  1249      
                                                                 
 binary_source (BinarySource  multiple                 0         
 )                                                               
                                                                 
 linear_encoder (LinearEncod  multiple                 0         
 er)                                                             
                                                                 
Total params: 1,249
Trainable params: 1,249
Non-trainable params: 0
_________________________________________________________________
Train params: [[1.0, 8.0, 4000, 0.001, 3000]] 

Step 0, loss =

Step 1800, loss = 0.046792
SNR [6.], ber = 7.34601e-05, bler = 7.28986e-04, block_num = 1380000,
ber: [7.34601449e-05]
bler: [0.00072899]
Step 1900, loss = 0.044262
SNR [6.], ber = 8.08521e-05, bler = 7.52060e-04, block_num = 1335000,
ber: [8.08520599e-05]
bler: [0.00075206]
Step 2000, loss = 0.047006
SNR [6.], ber = 7.71749e-05, bler = 7.34799e-04, block_num = 1365000,
ber: [7.71749084e-05]
bler: [0.0007348]
Step 2100, loss = 0.049367
SNR [6.], ber = 7.00424e-05, bler = 6.78644e-04, block_num = 1475000,
ber: [7.00423729e-05]
bler: [0.00067864]
Step 2200, loss = 0.050730
SNR [6.], ber = 7.92300e-05, bler = 7.61977e-04, block_num = 1315000,
ber: [7.9230038e-05]
bler: [0.00076198]
Step 2300, loss = 0.046625
SNR [6.], ber = 7.62184e-05, bler = 7.23466e-04, block_num = 1385000,
ber: [7.62184116e-05]
bler: [0.00072347]
Step 2400, loss = 0.042749
SNR [6.], ber = 7.73166e-05, bler = 7.75290e-04, block_num = 1295000,
ber: [7.73166023e-05]
bler: [0.00077529]
Step 2500, loss = 0.047638
SNR [6.],

Step 7800, loss = 0.047263
SNR [6.], ber = 7.80412e-05, bler = 7.67050e-04, block_num = 1305000,
ber: [7.80411877e-05]
bler: [0.00076705]
Step 7900, loss = 0.048532
SNR [6.], ber = 7.88116e-05, bler = 7.58333e-04, block_num = 1320000,
ber: [7.8811553e-05]
bler: [0.00075833]
Step 8000, loss = 0.047181
SNR [6.], ber = 7.57583e-05, bler = 7.36029e-04, block_num = 1360000,
ber: [7.57582721e-05]
bler: [0.00073603]
Step 8100, loss = 0.047969
SNR [6.], ber = 7.28348e-05, bler = 7.16429e-04, block_num = 1400000,
ber: [7.28348214e-05]
bler: [0.00071643]
Step 8200, loss = 0.047445
SNR [6.], ber = 7.07180e-05, bler = 6.94118e-04, block_num = 1445000,
ber: [7.07179931e-05]
bler: [0.00069412]
Step 8300, loss = 0.050783
SNR [6.], ber = 8.09263e-05, bler = 8.00797e-04, block_num = 1255000,
ber: [8.09262948e-05]
bler: [0.0008008]
Step 8400, loss = 0.044657
SNR [6.], ber = 7.57203e-05, bler = 7.44981e-04, block_num = 1345000,
ber: [7.57202602e-05]
bler: [0.00074498]
Step 8500, loss = 0.048739
SNR [6.],

Step 3400, loss = 0.048098
SNR [6.], ber = 8.04380e-05, bler = 7.89764e-04, block_num = 1270000,
ber: [8.04379921e-05]
bler: [0.00078976]
Step 3500, loss = 0.045087
SNR [6.], ber = 7.66038e-05, bler = 7.55472e-04, block_num = 1325000,
ber: [7.66037736e-05]
bler: [0.00075547]
Step 3600, loss = 0.045312
SNR [6.], ber = 7.42384e-05, bler = 7.20430e-04, block_num = 1395000,
ber: [7.42383513e-05]
bler: [0.00072043]
Step 3700, loss = 0.048333
SNR [6.], ber = 7.24650e-05, bler = 7.00699e-04, block_num = 1430000,
ber: [7.2465035e-05]
bler: [0.0007007]
Step 3800, loss = 0.045792
SNR [6.], ber = 7.55580e-05, bler = 7.15000e-04, block_num = 1400000,
ber: [7.55580357e-05]
bler: [0.000715]
Step 3900, loss = 0.045123
SNR [6.], ber = 7.30227e-05, bler = 7.28727e-04, block_num = 1375000,
ber: [7.30227273e-05]
bler: [0.00072873]
Step 4000, loss = 0.045863
SNR [6.], ber = 7.65449e-05, bler = 7.54307e-04, block_num = 1335000,
ber: [7.65449438e-05]
bler: [0.00075431]
Step 4100, loss = 0.048585
SNR [6.], b

Step 9400, loss = 0.043058
SNR [6.], ber = 7.57813e-05, bler = 7.17143e-04, block_num = 1400000,
ber: [7.578125e-05]
bler: [0.00071714]
Step 9500, loss = 0.050543
SNR [6.], ber = 7.30320e-05, bler = 6.94118e-04, block_num = 1445000,
ber: [7.30320069e-05]
bler: [0.00069412]
Step 9600, loss = 0.045904
SNR [6.], ber = 7.39955e-05, bler = 7.15000e-04, block_num = 1400000,
ber: [7.39955357e-05]
bler: [0.000715]
Step 9700, loss = 0.046473
SNR [6.], ber = 7.03390e-05, bler = 6.78644e-04, block_num = 1475000,
ber: [7.03389831e-05]
bler: [0.00067864]
Step 9800, loss = 0.047790
SNR [6.], ber = 7.11721e-05, bler = 6.92734e-04, block_num = 1445000,
ber: [7.11721453e-05]
bler: [0.00069273]
Step 9900, loss = 0.048325
SNR [6.], ber = 7.27176e-05, bler = 6.83959e-04, block_num = 1465000,
ber: [7.27175768e-05]
bler: [0.00068396]
SNR [1.], ber = 8.07125e-02, bler = 5.59400e-01, block_num = 10000,
SNR [2.], ber = 4.20312e-02, bler = 3.14500e-01, block_num = 10000,
SNR [3.], ber = 1.55406e-02, bler = 1.25

Step 5000, loss = 0.045819
SNR [6.], ber = 7.21611e-05, bler = 7.06338e-04, block_num = 1420000,
ber: [7.21610915e-05]
bler: [0.00070634]
Step 5100, loss = 0.049832
SNR [6.], ber = 7.99006e-05, bler = 7.58333e-04, block_num = 1320000,
ber: [7.99005682e-05]
bler: [0.00075833]
Step 5200, loss = 0.047749
SNR [6.], ber = 7.29537e-05, bler = 7.12456e-04, block_num = 1405000,
ber: [7.29537367e-05]
bler: [0.00071246]
Step 5300, loss = 0.044879
SNR [6.], ber = 7.54433e-05, bler = 7.10638e-04, block_num = 1410000,
ber: [7.54432624e-05]
bler: [0.00071064]
Step 5400, loss = 0.046858
SNR [6.], ber = 7.21767e-05, bler = 6.93793e-04, block_num = 1450000,
ber: [7.21767241e-05]
bler: [0.00069379]
Step 5500, loss = 0.046259
SNR [6.], ber = 7.46178e-05, bler = 7.20863e-04, block_num = 1390000,
ber: [7.46178058e-05]
bler: [0.00072086]
Step 5600, loss = 0.044199
SNR [6.], ber = 7.59055e-05, bler = 7.07420e-04, block_num = 1415000,
ber: [7.5905477e-05]
bler: [0.00070742]
Step 5700, loss = 0.047387
SNR [6.]

SNR [6.], ber = 6.53045e-05, bler = 6.47436e-04, block_num = 780000,
SNR [7.], ber = 4.41938e-06, bler = 4.95069e-05, block_num = 10140000,
SNR [8.], ber = 2.11563e-07, bler = 2.97000e-06, block_num = 100000000,
Load model from  ./gnn_dec_result/1107002623/model_mloss_4
Test codes 32 16 drl from ./Logs/1106074917/mat/episode_178step_1reward_10.555698805138144.txt
Test iteration:  30
SNR [1.], ber = 7.95281e-02, bler = 5.24400e-01, block_num = 10000,
SNR [2.], ber = 3.91781e-02, bler = 2.77200e-01, block_num = 10000,
SNR [3.], ber = 1.47000e-02, bler = 1.07400e-01, block_num = 10000,
SNR [4.], ber = 3.26562e-03, bler = 2.43333e-02, block_num = 30000,
SNR [5.], ber = 5.55208e-04, bler = 4.37500e-03, block_num = 120000,
SNR [6.], ber = 4.47917e-05, bler = 3.65942e-04, block_num = 1380000,
SNR [7.], ber = 2.40119e-06, bler = 2.12920e-05, block_num = 23530000,
SNR [8.], ber = 1.04062e-07, bler = 1.41000e-06, block_num = 100000000,
Load model from  ./gnn_dec_result/1107002623/model_mloss_4
T

In [3]:
n = 32
k = 16
code = 'drl'

file_h = './Logs/1106074917/mat/episode_178step_1reward_10.555698805138144.txt'
pcm = np.loadtxt(file_h, dtype=np.int32)
gnm = pcm2gm(pcm, verify_results=True)

num_iter_index = 8
multiloss_flag = True

tf.random.set_seed(2)
bp_decoder = GNN_Decoder(pcm = pcm,
                         num_iter = num_iter_index,
                         multiloss = multiloss_flag)
e2e_model = E2EModel(gnm, bp_decoder)

print('Code: ', n, ',', k, code, 'from', file_h)
print('Iteration: ', num_iter_index)
print('Multi-loss: ', multiloss_flag)

e2e_model(1, 1.) # call model once to init
e2e_model.summary()

# Training

In [4]:
train_params = [
    #batch_size, learning_rate, num_iter
    [1.0, 8.0, 4000, 1e-3, 3000]
]
print('Train params:', train_params, '\n')
train_model_gnn(e2e_model, train_params)
e2e_model.save_weights('./gnn_dec_result/'+time_now + '/model_mloss_1')
bers, blers = test_model_gnn(e2e_model, [1.0, 8.0, 100000, 10000, 500])
# print('BER:', bers)
# print('BLER:', blers)

train_params = [
    #batch_size, learning_rate, num_iter
    [1.0, 8.0, 4000, 1e-4, 10000]
]
print('Train params:', train_params, '\n')
train_model_gnn(e2e_model, train_params)
e2e_model.save_weights('./gnn_dec_result/'+time_now + '/model_mloss_2')
bers, blers = test_model_gnn(e2e_model, [1.0, 8.0, 100000, 10000, 500])
# print('BER:', bers)
# print('BLER:', blers)

train_params = [
    #batch_size, learning_rate, num_iter
    [1.0, 8.0, 4000, 1e-4, 10000]
]
print('Train params:', train_params, '\n')
train_model_gnn(e2e_model, train_params)
e2e_model.save_weights('./gnn_dec_result/'+time_now + '/model_mloss_3')
bers, blers = test_model_gnn(e2e_model, [1.0, 8.0, 100000, 10000, 500])
# print('BER:', bers)
# print('BLER:', blers)

train_params = [
    #batch_size, learning_rate, num_iter
    [1.0, 8.0, 4000, 1e-5, 10000]
]
print('Train params:', train_params, '\n')
train_model_gnn(e2e_model, train_params)
e2e_model.save_weights('./gnn_dec_result/'+time_now + '/model_mloss_4')
bers, blers = test_model_gnn(e2e_model, [1.0, 8.0, 100000, 10000, 500])
print('BER:', bers)
print('BLER:', blers)

# Testing

In [5]:
n_test = 32
k_test = 16
code = 'drl'

file_h_test = './Logs/1106074917/mat/episode_178step_1reward_10.555698805138144.txt'
pcm_test = np.loadtxt(file_h_test, dtype=np.int32)
gnm_test = pcm2gm(pcm_test, verify_results=True)

num_iter_index_test = 8
# multiloss_flag = True

tf.random.set_seed(2)
bp_decoder_test = GNN_Decoder(pcm = pcm_test, num_iter = num_iter_index_test)
e2e_model_test = E2EModel(gnm_test, bp_decoder_test)

model_fp = './gnn_dec_result/'+time_now + '/model_mloss_4'
e2e_model_test.load_weights(model_fp)

print('Load model from ', model_fp)
print('Test codes', n_test, k_test, code, 'from', file_h_test)
print('Test iteration: ', num_iter_index_test)

test_model_gnn(e2e_model_test, [1.0, 8.0, 10000, 10000, 500])

(array([8.09593750e-02, 4.11406250e-02, 1.58437500e-02, 4.10000000e-03,
        7.49218750e-04, 6.53044872e-05, 4.41937870e-06, 2.11562500e-07]),
 array([5.63000000e-01, 3.11100000e-01, 1.26400000e-01, 3.35000000e-02,
        6.66250000e-03, 6.47435897e-04, 4.95069034e-05, 2.97000000e-06]))

In [6]:
n_test = 32
k_test = 16
code = 'drl'

file_h_test = './Logs/1106074917/mat/episode_178step_1reward_10.555698805138144.txt'
pcm_test = np.loadtxt(file_h_test, dtype=np.int32)
gnm_test = pcm2gm(pcm_test, verify_results=True)

num_iter_index_test = 30
# multiloss_flag = True

tf.random.set_seed(2)
bp_decoder_test = GNN_Decoder(pcm = pcm_test, num_iter = num_iter_index_test)
e2e_model_test = E2EModel(gnm_test, bp_decoder_test)

model_fp = './gnn_dec_result/'+time_now + '/model_mloss_4'
e2e_model_test.load_weights(model_fp)

print('Load model from ', model_fp)
print('Test codes', n_test, k_test, code, 'from', file_h_test)
print('Test iteration: ', num_iter_index_test)

test_model_gnn(e2e_model_test, [1.0, 8.0, 10000, 10000, 500])

(array([7.95281250e-02, 3.91781250e-02, 1.47000000e-02, 3.26562500e-03,
        5.55208333e-04, 4.47916667e-05, 2.40118997e-06, 1.04062500e-07]),
 array([5.24400000e-01, 2.77200000e-01, 1.07400000e-01, 2.43333333e-02,
        4.37500000e-03, 3.65942029e-04, 2.12919677e-05, 1.41000000e-06]))

In [ ]:
n_test = 32
k_test = 16
code = 'drl'

file_h_test = './Logs/1106074917/mat/episode_178step_1reward_10.555698805138144.txt'
pcm_test = np.loadtxt(file_h_test, dtype=np.int32)
gnm_test = pcm2gm(pcm_test, verify_results=True)

num_iter_index_test = 50
# multiloss_flag = True

tf.random.set_seed(2)
bp_decoder_test = GNN_Decoder(pcm = pcm_test, num_iter = num_iter_index_test)
e2e_model_test = E2EModel(gnm_test, bp_decoder_test)

model_fp = './gnn_dec_result/'+time_now + '/model_mloss_4'
e2e_model_test.load_weights(model_fp)

print('Load model from ', model_fp)
print('Test codes', n_test, k_test, code, 'from', file_h_test)
print('Test iteration: ', num_iter_index_test)

test_model_gnn(e2e_model_test, [1.0, 8.0, 10000, 10000, 500])

In [ ]:
n_test = 32
k_test = 16
code = 'drl'

file_h_test = './Logs/1106074917/mat/episode_178step_1reward_10.555698805138144.txt'
pcm_test = np.loadtxt(file_h_test, dtype=np.int32)
gnm_test = pcm2gm(pcm_test, verify_results=True)

num_iter_index_test = 100
# multiloss_flag = True

tf.random.set_seed(2)
bp_decoder_test = GNN_Decoder(pcm = pcm_test, num_iter = num_iter_index_test)
e2e_model_test = E2EModel(gnm_test, bp_decoder_test)

model_fp = './gnn_dec_result/'+time_now + '/model_mloss_4'
e2e_model_test.load_weights(model_fp)

print('Load model from ', model_fp)
print('Test codes', n_test, k_test, code, 'from', file_h_test)
print('Test iteration: ', num_iter_index_test)

test_model_gnn(e2e_model_test, [1.0, 8.0, 10000, 10000, 500])